spring:
    application:
        name: greenhouse
    data:
        mongodb:
            uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/greenhouse?authSource=admin
            database: greenhouse
    autoconfigure:
        exclude: 
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

endpoints:
    esp-server:
        url: http://192.168.18.26:8080
        port: 8080
        endpoints:
            dht: /api/dht
            gpio: /api/gpio/%s/%d/%d
